# Generated by Django 4.2 on 2026-06-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='user',
            new_name='user_id',
        ),
    ]
