# Generated by Django 4.2 on 2026-06-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_user_addresses_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='user_id',
            new_name='user',
        ),
    ]
